%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%created by LSM
function dB0=Mag_randomGaussian
%====================================
p.DeltaX=0.001*randi(500);
p.DeltaY=0.001*randi(500);
p.DeltaZ=1000
p.PosX=0.001*randi(50);
p.PosY=0.001*randi(50);
p.PosZ=0;
p.Scale=5e-6;
disp(p.DeltaX);
disp(p.DeltaY);
disp(p.PosX);
disp(p.PosY);
dB0t=MagGaussian(p);
dB0=dB0t;
p=[];
%--------------------
end
