%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [t, ind, Disp, Axis, Ang]=Mot_WJGRotate
%====================================
p.Angle='0.6*sin(pi*t)';
p.Axis=[0;0;1];
p.dt=1e-3;
p.tEnd=4;
p.tStart=0;
[tt, Dispt, Axist, Angt]=MotRotate(p);
t=tt;
ind=ones(1,length(tt));
Disp=Dispt;
Axis=Axist;
Ang=Angt;
p=[];
%--------------------
end
