%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [t, ind, Disp, Axis, Ang]=Mot_blade8_cRotShift
%====================================
p.Direction=[round(rand());round(rand());0];
p.Displacement='(rand()*2-1)*0.22/128*5/0.2*t';
p.dt=1e-3;
p.tEnd=200e-3;
p.tStart=0e-3;
[tt, Dispt, Axist, Angt]=MotTranslate(p);
t=tt;
ind=ones(1,length(tt));
Disp=Dispt;
Axis=Axist;
Ang=Angt;
p=[];
%--------------------
p.Angle='(rand()*2-1)*pi/18/0.2*t';
p.Axis=[0;0;1];
p.dt=1e-3;
p.tEnd=200e-3;
p.tStart=0e-3;
[tt, Dispt, Axist, Angt]=MotRotate(p);
if isempty(Dispt) & ~isempty(Disp);
Disp=[Disp, zeros(3,length(tt))];
elseif ~isempty(Dispt) & isempty(Disp);
Disp=[zeros(3,length(t)), Dispt];
else Disp=[Disp, Dispt]; end;
if isempty(Axist) & ~isempty(Axis);
Axis=[Axis, Axis(:,end)*ones(1,length(tt))];
elseif ~isempty(Axist) & isempty(Axis);
Axis=[Axist(:,1)*ones(1,length(t)), Axist];
else Axis=[Axis, Axist]; end;
if isempty(Angt) & ~isempty(Ang);
Ang=[Ang, Ang(:,end)*ones(1,length(tt))];
elseif ~isempty(Angt) & isempty(Ang);
Ang=[zeros(1,length(t)), Angt];
else Ang=[Ang, Angt]; end;
t=[t, tt];
ind=[ind, 2 * ones(1,length(tt))];
p=[];
%--------------------
end
