%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version 1.3                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [rfAmp,rfPhase,rfFreq,rfCoil,GzAmp,GyAmp,GxAmp,ADC,Ext,uts,ts,flags]=PSD_OLEDMM
global VCtl
global VVar
CV1=75e-3;
CV10=0;
CV11=0;
CV2=80e-3;
CV3=0;
CV4=0;
CV5=0;
CV6=0;
CV7=0;
CV8=0;
CV9=0;
T1D=600e-3;
T2D=800e-3;
oledMM=1;
rfAmpAll=[];
rfPhaseAll=[];
rfFreqAll=[];
rfCoilAll=[];
GzAmpAll=[];
GyAmpAll=[];
GxAmpAll=[];
ADCAll=[];
ExtAll=[];
rfTimeAll=[];
GzTimeAll=[];
GyTimeAll=[];
GxTimeAll=[];
ADCTimeAll=[];
ExtTimeAll=[];
SEtAll=[];
uts=[];
ts=[];
flags=[];
if VCtl.PlotSeq == 1
rfAmp=[];
rfPhase=[];
rfFreq=[];
rfCoil=[];
GzAmp=[];
GyAmp=[];
GxAmp=[];
ADC=[];
Ext=[];
Freq=1;
Notes='regular TR section';
AttributeOpt={'on','off'};
Switch=AttributeOpt{1};
TREnd=Inf;
TRStart=1;
tE=VCtl.TR;
tS=0;
if VVar.TRCount<TRStart | VVar.TRCount>TREnd | mod(VVar.TRCount-TRStart,Freq)~=0 | strcmp(Switch,'off')
% do nothing
else
ts = [ts tS tE];
end
ts = [0 max(ts)-min(ts)];
return;
end
%==============Pulses 1==============
rfAmp=[];
rfPhase=[];
rfFreq=[];
rfCoil=[];
GzAmp=[];
GyAmp=[];
GxAmp=[];
ADC=[];
Ext=[];
rfTime=[];
GzTime=[];
GyTime=[];
GxTime=[];
ADCTime=[];
ExtTime=[];
Freq=1;
Notes='regular TR section';
AttributeOpt={'on','off'};
Switch=AttributeOpt{1};
TREnd=Inf;
TRStart=1;
tE=VCtl.TR;
tS=0;
if isempty(tS) | isempty(tE) | (tS>=tE)
error('SE setting is incorrect for Pulses 1!');
end
if VVar.TRCount<TRStart | VVar.TRCount>TREnd | mod(VVar.TRCount-TRStart,Freq)~=0 | strcmp(Switch,'off')
% do nothing
else
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=45;
p.Notes='excitation rf';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=4;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=1e-3;
p.tStart=0;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp1,rfPhase1,rfFreq1,rfCoil1,rfTime1]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil1(1)
rfAmp=[rfAmp rfAmp1];
rfPhase=[rfPhase rfPhase1];
rfFreq=[rfFreq rfFreq1];
rfCoil=[rfCoil rfCoil1];
rfTime=[rfTime rfTime1];
end
else
rfAmp=[rfAmp rfAmp1];
rfPhase=[rfPhase rfPhase1];
rfFreq=[rfFreq rfFreq1];
rfCoil=[rfCoil rfCoil1];
rfTime=[rfTime rfTime1];
end
end
p=[];
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=45;
p.Notes='excitation rf';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=4;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=VCtl.delta_TE*1+0.5e-3;
p.tStart=VCtl.delta_TE*1-0.5e-3;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp2,rfPhase2,rfFreq2,rfCoil2,rfTime2]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil2(1)
rfAmp=[rfAmp rfAmp2];
rfPhase=[rfPhase rfPhase2];
rfFreq=[rfFreq rfFreq2];
rfCoil=[rfCoil rfCoil2];
rfTime=[rfTime rfTime2];
end
else
rfAmp=[rfAmp rfAmp2];
rfPhase=[rfPhase rfPhase2];
rfFreq=[rfFreq rfFreq2];
rfCoil=[rfCoil rfCoil2];
rfTime=[rfTime rfTime2];
end
end
p=[];
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=180;
p.Notes='refocuse';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=6;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=VCtl.refocus+1e-3;
p.tStart=VCtl.refocus-1e-3;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp3,rfPhase3,rfFreq3,rfCoil3,rfTime3]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil3(1)
rfAmp=[rfAmp rfAmp3];
rfPhase=[rfPhase rfPhase3];
rfFreq=[rfFreq rfFreq3];
rfCoil=[rfCoil rfCoil3];
rfTime=[rfTime rfTime3];
end
else
rfAmp=[rfAmp rfAmp3];
rfPhase=[rfPhase rfPhase3];
rfFreq=[rfFreq rfFreq3];
rfCoil=[rfCoil rfCoil3];
rfTime=[rfTime rfTime3];
end
end
p=[];
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=90;
p.Notes='excitation rf';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=4;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=VCtl.T1D+0.5e-3;
p.tStart=VCtl.T1D-0.5e-3;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp4,rfPhase4,rfFreq4,rfCoil4,rfTime4]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil4(1)
rfAmp=[rfAmp rfAmp4];
rfPhase=[rfPhase rfPhase4];
rfFreq=[rfFreq rfFreq4];
rfCoil=[rfCoil rfCoil4];
rfTime=[rfTime rfTime4];
end
else
rfAmp=[rfAmp rfAmp4];
rfPhase=[rfPhase rfPhase4];
rfFreq=[rfFreq rfFreq4];
rfCoil=[rfCoil rfCoil4];
rfTime=[rfTime rfTime4];
end
end
p=[];
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=180;
p.Notes='refocuse';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=6;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=VCtl.T1D+60e-3+1e-3;
p.tStart=VCtl.T1D+60e-3-1e-3;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp5,rfPhase5,rfFreq5,rfCoil5,rfTime5]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil5(1)
rfAmp=[rfAmp rfAmp5];
rfPhase=[rfPhase rfPhase5];
rfFreq=[rfFreq rfFreq5];
rfCoil=[rfCoil rfCoil5];
rfTime=[rfTime rfTime5];
end
else
rfAmp=[rfAmp rfAmp5];
rfPhase=[rfPhase rfPhase5];
rfFreq=[rfFreq rfFreq5];
rfCoil=[rfCoil rfCoil5];
rfTime=[rfTime rfTime5];
end
end
p=[];
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=90;
p.Notes='excitation rf';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=4;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=VCtl.T2D+0.5e-3;
p.tStart=VCtl.T2D-0.5e-3;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp6,rfPhase6,rfFreq6,rfCoil6,rfTime6]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil6(1)
rfAmp=[rfAmp rfAmp6];
rfPhase=[rfPhase rfPhase6];
rfFreq=[rfFreq rfFreq6];
rfCoil=[rfCoil rfCoil6];
rfTime=[rfTime rfTime6];
end
else
rfAmp=[rfAmp rfAmp6];
rfPhase=[rfPhase rfPhase6];
rfFreq=[rfFreq rfFreq6];
rfCoil=[rfCoil rfCoil6];
rfTime=[rfTime rfTime6];
end
end
p=[];
%--------------------
AttributeOpt={'on','off'};
p.AnchorTE=AttributeOpt{2};
AttributeOpt={'Non','Hamming','Hanning'};
p.Apod=AttributeOpt{2};
p.CoilID=1;
p.DupSpacing=0;
p.Duplicates=1;
p.FA=180;
p.Notes='refocuse';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.TBP=6;
p.dt=20e-6;
p.rfFreq=0;
p.rfPhase=0;
p.tEnd=VCtl.T2D+60e-3+1e-3;
p.tStart=VCtl.T2D+60e-3-1e-3;
if strcmp(p.Switch,'on')
if strcmp(p.AnchorTE,'on')
switch VCtl.TEAnchor
case 'Start'
VCtl.TEAnchorTime=p.tStart; 
case 'Middle'
VCtl.TEAnchorTime=(p.tStart+p.tEnd)/2; 
case 'End'
VCtl.TEAnchorTime=p.tEnd;
end
end
[rfAmp7,rfPhase7,rfFreq7,rfCoil7,rfTime7]=rfSinc(p);
if strcmp(VCtl.MultiTransmit,'off')
if VCtl.MasterTxCoil==rfCoil7(1)
rfAmp=[rfAmp rfAmp7];
rfPhase=[rfPhase rfPhase7];
rfFreq=[rfFreq rfFreq7];
rfCoil=[rfCoil rfCoil7];
rfTime=[rfTime rfTime7];
end
else
rfAmp=[rfAmp rfAmp7];
rfPhase=[rfPhase rfPhase7];
rfFreq=[rfFreq rfFreq7];
rfCoil=[rfCoil rfCoil7];
rfTime=[rfTime rfTime7];
end
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher_L';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=70e-3;
p.tStart=69e-3;
if strcmp(p.Switch,'on')
[GzAmp1,GzTime1]=GzAreaTrapezoid(p);
GzAmp=[GzAmp GzAmp1];
GzTime=[GzTime GzTime1];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher_L';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=79e-3;
p.tStart=78e-3;
if strcmp(p.Switch,'on')
[GzAmp2,GzTime2]=GzAreaTrapezoid(p);
GzAmp=[GzAmp GzAmp2];
GzTime=[GzTime GzTime2];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher_L';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=655e-3;
p.tStart=652e-3;
if strcmp(p.Switch,'on')
[GzAmp3,GzTime3]=GzAreaTrapezoid(p);
GzAmp=[GzAmp GzAmp3];
GzTime=[GzTime GzTime3];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher_L';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=670e-3;
p.tStart=667e-3;
if strcmp(p.Switch,'on')
[GzAmp4,GzTime4]=GzAreaTrapezoid(p);
GzAmp=[GzAmp GzAmp4];
GzTime=[GzTime GzTime4];
end
p=[];
%--------------------
p.Gy1Sign=-1;
p.Gy2Sign=1;
p.Notes='EPI phase encoding';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.t1Start=[];
p.t2Middle=VCtl.TE;
if strcmp(p.Switch,'on')
[GyAmp1,GyTime1]=GyOLEDMM(p);
GyAmp=[GyAmp GyAmp1];
GyTime=[GyTime GyTime1];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=70e-3;
p.tStart=69e-3;
if strcmp(p.Switch,'on')
[GyAmp2,GyTime2]=GyAreaTrapezoid(p);
GyAmp=[GyAmp GyAmp2];
GyTime=[GyTime GyTime2];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=79e-3;
p.tStart=78e-3;
if strcmp(p.Switch,'on')
[GyAmp3,GyTime3]=GyAreaTrapezoid(p);
GyAmp=[GyAmp GyAmp3];
GyTime=[GyTime GyTime3];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=655e-3;
p.tStart=652e-3;
if strcmp(p.Switch,'on')
[GyAmp4,GyTime4]=GyAreaTrapezoid(p);
GyAmp=[GyAmp GyAmp4];
GyTime=[GyTime GyTime4];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=670e-3;
p.tStart=667e-3;
if strcmp(p.Switch,'on')
[GyAmp5,GyTime5]=GyAreaTrapezoid(p);
GyAmp=[GyAmp GyAmp5];
GyTime=[GyTime GyTime5];
end
p=[];
%--------------------
p.Gx1Sign=-1;
p.Gx2Sign=1;
p.Notes='EPI frequency encoding';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.t1Start=[];
p.t2Middle=VCtl.TE;
if strcmp(p.Switch,'on')
[GxAmp1,GxTime1]=GxOLEDMM(p);
GxAmp=[GxAmp GxAmp1];
GxTime=[GxTime GxTime1];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=70e-3;
p.tStart=69e-3;
if strcmp(p.Switch,'on')
[GxAmp2,GxTime2]=GxAreaTrapezoid(p);
GxAmp=[GxAmp GxAmp2];
GxTime=[GxTime GxTime2];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=79e-3;
p.tStart=78e-3;
if strcmp(p.Switch,'on')
[GxAmp3,GxTime3]=GxAreaTrapezoid(p);
GxAmp=[GxAmp GxAmp3];
GxTime=[GxTime GxTime3];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=655e-3;
p.tStart=652e-3;
if strcmp(p.Switch,'on')
[GxAmp4,GxTime4]=GxAreaTrapezoid(p);
GxAmp=[GxAmp GxAmp4];
GxTime=[GxTime GxTime4];
end
p=[];
%--------------------
p.Area=CV8;
p.DupSpacing=0;
p.Duplicates=1;
p.Notes='crusher';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tEnd=670e-3;
p.tStart=667e-3;
if strcmp(p.Switch,'on')
[GxAmp5,GxTime5]=GxAreaTrapezoid(p);
GxAmp=[GxAmp GxAmp5];
GxTime=[GxTime GxTime5];
end
p=[];
%--------------------
p.Notes='EPI readout';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tMiddle=VCtl.TE;
if strcmp(p.Switch,'on')
[ADC1,ADCTime1]=ADCEPIM(p);
ADC=[ADC ADC1];
ADCTime=[ADCTime ADCTime1];
end
p=[];
%--------------------
p.DupSpacing=0;
p.Duplicates=1;
p.Ext=1;
p.Notes='reset K space location';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tStart=CV1/3;
if strcmp(p.Switch,'on')
[Ext1,ExtTime1]=ExtBit(p);
Ext=[Ext Ext1];
ExtTime=[ExtTime ExtTime1];
end
p=[];
%--------------------
p.DupSpacing=0;
p.Duplicates=1;
p.Ext=5;
p.Notes='calculate remaining scan time';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tStart=0;
if strcmp(p.Switch,'on')
[Ext2,ExtTime2]=ExtBit(p);
Ext=[Ext Ext2];
ExtTime=[ExtTime ExtTime2];
end
p=[];
%--------------------
p.DupSpacing=0;
p.Duplicates=1;
p.Ext=6;
p.Notes='IdealSpoiler';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tStart=VCtl.T1D-10e-3;
if strcmp(p.Switch,'on')
[Ext3,ExtTime3]=ExtBit(p);
Ext=[Ext Ext3];
ExtTime=[ExtTime ExtTime3];
end
p=[];
%--------------------
p.DupSpacing=0;
p.Duplicates=1;
p.Ext=1;
p.Notes='reset K space location';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tStart=VCtl.T1D-8e-3;
if strcmp(p.Switch,'on')
[Ext4,ExtTime4]=ExtBit(p);
Ext=[Ext Ext4];
ExtTime=[ExtTime ExtTime4];
end
p=[];
%--------------------
p.DupSpacing=0;
p.Duplicates=1;
p.Ext=6;
p.Notes='IdealSpoiler';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{2};
p.tStart=VCtl.T2D-10e-3;
if strcmp(p.Switch,'on')
[Ext5,ExtTime5]=ExtBit(p);
Ext=[Ext Ext5];
ExtTime=[ExtTime ExtTime5];
end
p=[];
%--------------------
p.DupSpacing=0;
p.Duplicates=1;
p.Ext=1;
p.Notes='reset K space location';
AttributeOpt={'on','off'};
p.Switch=AttributeOpt{1};
p.tStart=VCtl.T2D-8e-3;
if strcmp(p.Switch,'on')
[Ext6,ExtTime6]=ExtBit(p);
Ext=[Ext Ext6];
ExtTime=[ExtTime ExtTime6];
end
p=[];
%--------------------
SEt=[tS tE];
rfAmp(rfTime<0 | rfTime>SEt(2)-SEt(1)) = [];
rfPhase(rfTime<0 | rfTime>SEt(2)-SEt(1)) = [];
rfFreq(rfTime<0 | rfTime>SEt(2)-SEt(1)) = [];
rfCoil(rfTime<0 | rfTime>SEt(2)-SEt(1)) = [];
GzAmp(GzTime<0 | GzTime>SEt(2)-SEt(1)) = [];
GyAmp(GyTime<0 | GyTime>SEt(2)-SEt(1)) = [];
GxAmp(GxTime<0 | GxTime>SEt(2)-SEt(1)) = [];
ADC(ADCTime<0 | ADCTime>SEt(2)-SEt(1)) = [];
Ext(ExtTime<0 | ExtTime>SEt(2)-SEt(1)) = [];
rfTime(rfTime<0 | rfTime>SEt(2)-SEt(1)) = [];
GzTime(GzTime<0 | GzTime>SEt(2)-SEt(1)) = [];
GyTime(GyTime<0 | GyTime>SEt(2)-SEt(1)) = [];
GxTime(GxTime<0 | GxTime>SEt(2)-SEt(1)) = [];
ADCTime(ADCTime<0 | ADCTime>SEt(2)-SEt(1)) = [];
ExtTime(ExtTime<0 | ExtTime>SEt(2)-SEt(1)) = [];
rfAmp(abs(rfAmp)<eps) = 0;
rfTime = rfTime + SEt(1);
GzTime = GzTime + SEt(1);
GyTime = GyTime + SEt(1);
GxTime = GxTime + SEt(1);
ADCTime = ADCTime + SEt(1);
ExtTime = ExtTime + SEt(1);
rfAmpAll=[rfAmpAll rfAmp];
rfPhaseAll=[rfPhaseAll rfPhase];
rfFreqAll=[rfFreqAll rfFreq];
rfCoilAll=[rfCoilAll rfCoil];
GzAmpAll=[GzAmpAll GzAmp];
GyAmpAll=[GyAmpAll GyAmp];
GxAmpAll=[GxAmpAll GxAmp];
ADCAll=[ADCAll ADC];
ExtAll=[ExtAll Ext];
rfTimeAll=[rfTimeAll rfTime];
GzTimeAll=[GzTimeAll GzTime];
GyTimeAll=[GyTimeAll GyTime];
GxTimeAll=[GxTimeAll GxTime];
ADCTimeAll=[ADCTimeAll ADCTime];
ExtTimeAll=[ExtTimeAll ExtTime];
SEtAll=[SEtAll SEt];
end
%====================================
if isempty(rfTimeAll)
error('rf sequence line can not be empty! Master Tx coil element must be used.');
end
if isempty(GzTimeAll)
error('GzSS sequence line can not be empty!');
end
if isempty(GyTimeAll)
error('GyPE sequence line can not be empty!');
end
if isempty(GxTimeAll)
error('GxR sequence line can not be empty!');
end
if isempty(ADCTimeAll)
error('ADC sequence line can not be empty!');
end
if isempty(ExtTimeAll)
error('Ext sequence line can not be empty!');
end
SEflag=repmat([0 0 0 0 0 0]',[1 2]);
rfflag=repmat([1 0 0 0 0 0]',[1 max(size(rfTimeAll))]);
Gzflag=repmat([0 1 0 0 0 0]',[1 max(size(GzTimeAll))]);
Gyflag=repmat([0 0 1 0 0 0]',[1 max(size(GyTimeAll))]);
Gxflag=repmat([0 0 0 1 0 0]',[1 max(size(GxTimeAll))]);
ADCflag=repmat([0 0 0 0 1 0]',[1 max(size(ADCTimeAll))]);
Extflag=repmat([0 0 0 0 0 1]',[1 max(size(ExtTimeAll))]);
ts=[[min(SEtAll) max(SEtAll)] rfTimeAll GzTimeAll GyTimeAll GxTimeAll ADCTimeAll ExtTimeAll]-min(SEtAll);
flags=[SEflag rfflag Gzflag Gyflag Gxflag ADCflag Extflag];
[ts,ind]=sort(ts);
uts=unique(ts);
flags=flags(:,ind);
[rfTime,ind]=sort(rfTimeAll-min(SEtAll));
rfAmp=rfAmpAll(:,ind);
rfPhase=rfPhaseAll(:,ind);
rfFreq=rfFreqAll(:,ind);
rfCoil=rfCoilAll(:,ind);
[GzTime,ind]=sort(GzTimeAll-min(SEtAll));
GzAmp=GzAmpAll(:,ind);
[GyTime,ind]=sort(GyTimeAll-min(SEtAll));
GyAmp=GyAmpAll(:,ind);
[GxTime,ind]=sort(GxTimeAll-min(SEtAll));
GxAmp=GxAmpAll(:,ind);
[ADCTime,ind]=sort(ADCTimeAll-min(SEtAll));
ADC=ADCAll(:,ind);
[ExtTime,ind]=sort(ExtTimeAll-min(SEtAll));
Ext=ExtAll(:,ind);
rfAmp(1) = 0;
rfPhase(1) = 0;
rfFreq(1) = 0;
GzAmp(1) = 0;
GyAmp(1) = 0;
GxAmp(1) = 0;
ADC(1) = 0;
Ext(1) = 0;
rfAmp(end) = 0;
rfPhase(end) = 0;
rfFreq(end) = 0;
GzAmp(end) = 0;
GyAmp(end) = 0;
GxAmp(end) = 0;
ADC(end) = 0;
Ext(end) = 0;
end
